name: K8s Workflow

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "K8s Image for ${{ inputs.image }}"
  docker-tag:
    runs-on: ubuntu-latest
    steps:
    - run: echo "K8s Tagging Image ${{ inputs.image }}"
